stages:
  - build
  - deploy

variables:
  MAVEN_REPO_LOCAL: .m2/repository
  GIT_STRATEGY: clone
  HOST_PORT: 80
  CONTAINER_PORT: 8080
  DB_URL: jdbc:postgresql://postgres:5432/cards-db

.build:
  stage: build
  image: "maven:3.8.3-openjdk-17"
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - $MAVEN_REPO_LOCAL
  tags:
    - school2023team4

build:
  extends: .build
  script:
    - chmod +x mvnw
    - ./mvnw -s .m2/settings.xml spring-boot:build-image
  only:
    refs:
      - main

build_mr:
  extends: .build
  script:
    - chmod +x mvnw
    - ./mvnw -s .m2/settings.xml install
  only:
    - merge_requests

deploy:
  stage: deploy
  image: "docker/compose:1.25.1"
  variables:
    HOST_PORT: "8082"
    CONTAINER_PORT: "8082"
  script:
    - docker stop ${CI_PROJECT_NAME}-$HOST_PORT || true
    - docker rm ${CI_PROJECT_NAME}-$HOST_PORT || true
    - docker network create -d bridge hipstercard-network || true
    - docker run -d --name ${CI_PROJECT_NAME}-$HOST_PORT --network hipstercard-network -p $HOST_PORT:$CONTAINER_PORT -e SPRING_DATASOURCE_URL=$DB_URL ${CI_PROJECT_NAME}:1.0.0-team4
  only:
    refs:
      - main
  tags:
    - school2023team4


