spring:
  application:
    name: cards-service

server:
  port: 8080

#eureka:
#  client:
#    preferIpAddress: true
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone:
#        http://localhost:8070/eureka/

