spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  application:
    name: cards-service
  datasource:
    url: jdbc:postgresql://postgres:5432/cards-db
    username: hipstercard-db-user
    password: hipstercard-db-password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog.xml

server:
  port: 8080
