spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  application:
    name: cards-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cards-db
    username: cards-db-user
    password: cards-db-password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
